# EDA sobre discapacidad reconocida en España

Este proyecto analiza la evolución y distribución de los registros de discapacidad reconocida en España entre 2019 y 2024.

El objetivo principal es explorar los datos, limpiarlos si es necesario, visualizar patrones relevantes y extraer conclusiones comprensibles.

In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from bokeh.plotting import figure, show, output_notebook
from bokeh.models import HoverTool

from pathlib import Path

Path.cwd()

output_notebook()

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

sns.set_theme(style="whitegrid")

## Carga del dataset

El archivo `bdepcd_2024.csv` se encuentra incluido en este repositorio.  
Contiene datos públicos sobre discapacidad reconocida en España entre 2019 y 2024.

In [12]:
list(Path.cwd().glob("*"))

url = "https://raw.githubusercontent.com/Bootcamp-IA-MAD-P7/project3-EDA-Fernanda/main/bdepcd_2024.csv"

df = pd.read_csv(url, encoding="utf-8-sig", sep=None, engine="python")

df.head()

,Año,Comunidad_Autónoma,Provincia,Grupo_DIAG0,Sexo,Grupo_grado_discapacidad,Grupo_edad,Valor
0,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 18 a 34 años,33
1,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 35 a 64 años,367
2,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 65 a 79 años,397
3,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 7 a 17 años,6
4,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 80 años o más,164

In [13]:
df.shape

(148626, 8)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 148626 entries, 0 to 148625
Data columns (total 8 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Año                       148626 non-null  int64
 1   Comunidad_Autónoma        148626 non-null  str
 2   Provincia                 148626 non-null  str
 3   Grupo_DIAG0               148626 non-null  str
 4   Sexo                      148626 non-null  str
 5   Grupo_grado_discapacidad  148626 non-null  str
 6   Grupo_edad                148626 non-null  str
 7   Valor                     148626 non-null  int64
dtypes: int64(2), str(6)
memory usage: 9.1 MB

In [15]:
df.head()

,Año,Comunidad_Autónoma,Provincia,Grupo_DIAG0,Sexo,Grupo_grado_discapacidad,Grupo_edad,Valor
0,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 18 a 34 años,33
1,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 35 a 64 años,367
2,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 65 a 79 años,397
3,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 7 a 17 años,6
4,2019,Andalucía,Almería,"Cardiovascular, hematológica, inmunológica o r...",H,De 33% a 44%,De 80 años o más,164

In [16]:
df.isnull().sum()

Año                         0
Comunidad_Autónoma          0
Provincia                   0
Grupo_DIAG0                 0
Sexo                        0
Grupo_grado_discapacidad    0
Grupo_edad                  0
Valor                       0
dtype: int64

In [17]:
df.describe(include="all")

,Año,Comunidad_Autónoma,Provincia,Grupo_DIAG0,Sexo,Grupo_grado_discapacidad,Grupo_edad,Valor
count,148626.000000,148626,148626,148626,148626,148626,148626,148626.000000
unique,NaN,19,52,10,2,5,6,NaN
top,NaN,Andalucía,Madrid,Otra deficiencia,H,De 33% a 44%,De 35 a 64 años,NaN
freq,NaN,24355,3294,18350,75050,31833,27908,NaN
mean,2021.537234,NaN,NaN,NaN,NaN,NaN,NaN,187.013006
std,1.716856,NaN,NaN,NaN,NaN,NaN,NaN,595.940228
min,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,6.000000
50%,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN,33.000000
75%,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,138.000000
max,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,15572.000000

In [18]:
df.duplicated().sum()

np.int64(0)